apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: deployment1
  template:
    metadata:
      labels:
        name: deployment1
    spec:
      containers:
        - name: c00
          image: sasank2126/testimg
          ports:
            - containerPort: 80
