name: Secrets Demo

on:
  push:
    branches:
      - master

jobs:

  demo:
    runs-on: ubuntu-latest

    steps:

      - name: Test Secret
        run: |
          echo "Docker username is:"
          echo "${{ secrets.DOCKER_USERNAME }}"

          echo "Docker password is:"
          echo "${{ secrets.DOCKER_PASSWORD }}"
